repos:
- repo: https://repo1.dsop.io/platform-one/plugins/pre-commit-bootstraps.git
  rev: v0.2.0
  hooks:
    # Gatekeeper
    - id: kustomize
      name: validate kustomize - opa gatekeeper
      args:
        - deploy/opa-gatekeeper

    # Core Contraint Templates
    - id: kustomize
      name: validate kustomize - core contraint templates
      args:
        - deploy/contraint-templates/core

    # Core Contraints
    - id: kustomize
      name: validate kustomize - core contraints
      args:
        - deploy/constraints/core
