apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: '{{ template "gatekeeper.name" . }}'
    chart: '{{ template "gatekeeper.name" . }}'
    gatekeeper.sh/system: "yes"
    heritage: '{{ .Release.Service }}'
    release: '{{ .Release.Name }}'
  name: gatekeeper-admin
  namespace: '{{ .Release.Namespace }}'
{{/* start BB addition 
If false, a K8s API token will not be mounted in Pods utilizing this ServiceAccount, unless overriden at the Pod spec-level
In this case, this behavior -is- overriden at the Pod spec-level due to app requirements
*/}}
automountServiceAccountToken: false
{{/* end BB addition */}}