apiVersion: config.gatekeeper.sh/v1alpha1
kind: Config
metadata:
  name: config
  namespace: '{{ .Release.Namespace }}'
  labels:
    {{- include "gatekeeper.labels" . | nindent 4 }}
spec:
  match:
    {{- if .Values.openshift }}
    - excludedNamespaces: [ "kube-*", "{{ .Release.Namespace }}", "openshift*"]
      processes: [ "*" ]
    {{- else }}
    - excludedNamespaces: [ "kube-system", "{{ .Release.Namespace }}" ]
      processes: [ "*" ]
    {{- end }}
  sync:
    syncOnly:
      - group: "networking.k8s.io"
        version: "v1"
        kind: "Ingress"
      - group: ""
        version: "v1"
        kind: "Namespace"
      - group: ""
        version: "v1"
        kind: "Pod"
      - group: ""
        version: "v1"
        kind: Service
