namespace: gatekeeper-system

resources:
  - opa-gatekeeper

  # Global configs for gatekeeper
  - configs

  # Core constraint templates
  - contraint-templates/core

  # Core constraints
  # - constraints/core
