{{- /* This template adds user-defined additional network policies if enabled in values.yaml. */ -}}
{{- if and .Values.networkPolicies.enabled .Values.networkPolicies.additionalPolicies }}
{{- range $policy := .Values.networkPolicies.additionalPolicies }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $policy.name | quote }}
spec:
  {{- tpl ($policy.spec | toYaml) $ | nindent 2 }}
---
{{- end }}
{{- end }}
